server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: 192.168.1.4:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
