server:
  port: 9002

spring:
  application:
    name: nacos-email-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 192.168.111.144:1111  # Nginx IP:PORT

management:
  endpoints:
    web:
      exposure:
        include: '*'
