server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #default port is 8719. If 8719 is used, "port" will automatically increase 1.
        port: 8719

service-url:
  nacos-user-service: http://nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'

#  //========= Does not work
#feign:
#  sentinel:
#    enabled: true
#  hystrix:
#    enabled: true

#ribbon:
#  eureka:
#    enabled: true