server:
  port: 9001

spring:
  application:
    name: nacos-email-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: http://47.101.219.248:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
