server:
  port: 83

spring:
  application:
    name: nacos-email-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-email-provider
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
